language: swift

osx_image: xcode10.1
xcode_project: Bootcamp.xcodeproj

cache:
  bundler: true
  directories:
    - Carthage
    - node_modules

before_install:
  - nvm install 10
  - nvm alias default 10

install:
  - carthage update --no-use-binaries --cache-builds --platform iOS

script:
  - swiftlint
  - xcodebuild -scheme BootcampTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' test | xcpretty
  - xcodebuild -scheme BootcampUITests -sdk iphonesimulator build-for-testing -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack: web-bootcamp:wyKIbU3rSC2tjbCh99Nnq1aE
