language: swift

osx_image: xcode9.4
xcode_project: Bootcamp.xcodeproj

cache:
  bundler: true
  directories:
    - Carthage
    - node_modules

before_install:
  - nvm install 10
  - nvm alias default 10

install:
  - carthage update --no-use-binaries --cache-builds --platform iOS
  - gem install fir-cli

script:
  - swiftlint
  - xcodebuild -scheme BootcampTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' test | xcpretty
  - xcodebuild -scheme BootcampUITests -sdk iphonesimulator build-for-testing -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  # https://docs.travis-ci.com/user/common-build-problems/#Mac%3A-macOS-Sierra-(10.12)-Code-Signing-Errors
  - security create-keychain -p travis ios-build.keychain
  - security default-keychain -s ios-build.keychain
  - security unlock-keychain -p travis ios-build.keychain

  # Add certificates to keychain and allow codesign to access them
  - security import .travis/Certificates.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security import .travis/Certificates.p12 -P "${CERT_PASSWORD}" -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
  - security set-key-partition-list -S "apple-tool:,apple:" -s -k travis ios-build.keychain

  - open .travis/9ad39aca-fbf8-4632-9c52-fed399577db3.mobileprovision

deploy:
  provider: script
  skip_cleanup: true
  script: sh .travis/deploy.sh
  on:
    branch: master

notifications:
  email: false
  slack: web-bootcamp:wyKIbU3rSC2tjbCh99Nnq1aE
